### ISSUE TITLE
Extension method for modelless processing extends Controller instead of ControllerBase

### ISSUE THREAD

**Issue by gvas** [ma1f/uploadstream#2]
The non-generic StreamFiles() extension method should extend ControllerBase instead of Controller, just like its generic counterpart. Currently Web API controllers can't use it.

**Comment by ma1f** [comment]
Thanks, will look into updating shortly, as well as updating to latest dotnet 2.2/3 - been quite busy lately..

**Comment by PrinceOwen9466** [comment]
The generic StreamFiles() extension method seems to make reader.ReadNextSectionAsync() recursive everytime it makes the UpdateModel<T> call. The problem with that is that the MultipartReader keeps re-reading files even when they have already been read, therefore leading to an exception with the following message => "Unexpected end of Stream, the content may have already been read by another component".

I'm not sure if there's an easy workaround for that issue, but for the meantime, I was able to get things working fine like this:


`
await this.Request.StreamFilesModel(async file =>
{
    using (var stream = file.OpenReadStream)
        ....
}
`

It would really be great if the non-generic version of `StreamFiles()` could be made to work with ControllerBase.

**Comment by ma1f** [comment]
Updated project to dotnet core v3.1 and made the generic version work with `ControllerBase`
