### ISSUE TITLE
Support for controller that does not inherit from Controller/ControllerBase 

### ISSUE THREAD

**Issue by candoumbe** [ma1f/uploadstream#3]
Hi !

Very nice work you've done so far.
I wonder if it could be possible to have a static method with the same behavior so that it could be used with controller that does not inherit from `Controller`/`ControllerBase`.

In most netcore API I work on, I try to have controllers that doesn't not extend Controller/ControllerBase and it would be nice to be able to seamlessly perform streaming upload/download in such cases 

Let met know if you need any additional information (or help ?) on this...

**Comment by ma1f** [comment]
Hey thanks, the controller is required for updating model/ModelState but have `HttpRequest` extension as well if that's all you need - look at `HttpRequestExtensions.cs` or else `ControllerExtensions.cs` where I implement it - should work off any `HttpRequest`.
```
var form = await Request.StreamFilesModel(func);
// if you do not need the form model just await, ie.
await Request.StreamFilesModel(func);
```
